spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employees
    username: postgres
    password: pass
#  flyway:
#    enabled: false
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: validate
    show-sql: true
    properties:
      # Hibernate Properties
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
##spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
  endpoint:
    health:
      show-details: always
